apiVersion: v1
kind: Service
metadata:
  name: project-node-port

spec:
  type: NodePort
  selector:
    app: palestine
  ports:
    - port: 8080 # Cluster IP servic port
      targetPort: 80 # pod container port
      nodePort: 30005 # port for node



